// Neon Auth + Data API authenticated layer. Public endpoints only; no privileged secrets.
const ARAPONGAS_AUTH='https://ep-delicate-recipe-ac7oxhhf.neonauth.sa-east-1.aws.neon.tech/arapongas_digital/auth';
const ARAPONGAS_DATA='https://ep-delicate-recipe-ac7oxhhf.apirest.sa-east-1.aws.neon.tech/arapongas_digital/rest/v1';let cachedJwt=null;const enc=v=>encodeURIComponent(String(v??''));
async function authRequest(path,options={}){const response=await fetch(`${ARAPONGAS_AUTH}${path}`,{credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json',...(options.headers||{})},...options});let data=null;try{data=await response.json()}catch{}if(!response.ok)throw new Error(data?.message||data?.error||`Auth ${response.status}`);const jwt=response.headers.get('set-auth-jwt');if(jwt){cachedJwt=jwt;if(data?.session)data.session.token=jwt;else if(data?.data?.session)data.data.session.token=jwt}return data}
async function session(){const data=await authRequest('/get-session',{method:'GET'});const token=data?.session?.token||data?.data?.session?.token;if(token)cachedJwt=token;return data}async function jwt(){if(cachedJwt)return cachedJwt;const s=await session();return s?.session?.token||s?.data?.session?.token||cachedJwt||null}
async function dataRequest(resource,{method='GET',query='',body,prefer}={}){const token=await jwt();if(!token)throw new Error('Sessão autenticada sem token de dados.');const headers={Accept:'application/json',Authorization:`Bearer ${token}`};if(body!==undefined)headers['Content-Type']='application/json';if(prefer)headers.Prefer=prefer;const response=await fetch(`${ARAPONGAS_DATA}/${resource}${query}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});let data=null;try{data=await response.json()}catch{}if(!response.ok)throw new Error(data?.message||data?.details||`Data API ${response.status}`);return data}
async function currentProfile(){const rows=await dataRequest('profiles',{query:'?select=id,auth_user_id,full_name,phone,role,city_id,avatar_url,active,created_at&limit=1'});return Array.isArray(rows)?rows[0]||null:null}async function requireAdmin(){const p=await currentProfile();if(!p?.active||!['admin','superadmin'].includes(p.role))throw new Error('Acesso administrativo negado.');return p}
async function ensureProfile(user){if(!user?.id)throw new Error('Usuário autenticado inválido.');let profile=await currentProfile();if(profile)return profile;const rows=await dataRequest('profiles',{method:'POST',body:{auth_user_id:String(user.id),full_name:String(user.name||'').trim()||null,role:'consumer'},prefer:'return=representation'});profile=Array.isArray(rows)?rows[0]||null:null;if(!profile)profile=await currentProfile();return profile}
async function updateProfile(changes={}){const allowed={};if(Object.prototype.hasOwnProperty.call(changes,'full_name'))allowed.full_name=String(changes.full_name||'').trim().slice(0,160)||null;if(Object.prototype.hasOwnProperty.call(changes,'phone'))allowed.phone=String(changes.phone||'').replace(/[^0-9+() -]/g,'').trim().slice(0,30)||null;if(Object.prototype.hasOwnProperty.call(changes,'city_id'))allowed.city_id=changes.city_id||null;if(Object.prototype.hasOwnProperty.call(changes,'avatar_url'))allowed.avatar_url=changes.avatar_url||null;if(!Object.keys(allowed).length)return currentProfile();const rows=await dataRequest('profiles',{method:'PATCH',query:'?select=id,auth_user_id,full_name,phone,role,city_id,avatar_url,active',body:allowed,prefer:'return=representation'});return Array.isArray(rows)?rows[0]||null:null}
async function merchantRequests(){const p=await currentProfile();if(!p)return[];const rows=await dataRequest('merchant_requests',{query:`?select=id,business_name,document,whatsapp,category_id,status,admin_notes,created_at,reviewed_at&profile_id=eq.${enc(p.id)}&order=created_at.desc`});return Array.isArray(rows)?rows:[]}async function adminMerchantRequests(status='pending'){await requireAdmin();const safe=['pending','approved','rejected','cancelled'].includes(status)?status:'pending';const rows=await dataRequest('merchant_requests',{query:`?select=id,profile_id,city_id,business_name,document,whatsapp,category_id,status,admin_notes,created_at,reviewed_at&status=eq.${enc(safe)}&order=created_at.asc`});return Array.isArray(rows)?rows:[]}
function slugify(value=''){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120)}
async function approveMerchantRequest(requestId,businessName,customSlug=''){await requireAdmin();const id=String(requestId||'').trim();if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('Solicitação inválida.');const slug=slugify(customSlug||businessName);if(!slug)throw new Error('Não foi possível gerar o endereço da empresa.');const result=await dataRequest('rpc/admin_approve_merchant_request',{method:'POST',body:{p_request_id:id,p_slug:slug}});const businessId=Array.isArray(result)?result[0]??null:result;if(!businessId)throw new Error('A solicitação não pôde ser aprovada. Verifique se ainda está pendente e se o perfil já possui empresa.');return{businessId,slug}}
async function rejectMerchantRequest(requestId,notes=''){await requireAdmin();const id=String(requestId||'').trim();if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('Solicitação inválida.');const result=await dataRequest('rpc/admin_reject_merchant_request',{method:'POST',body:{p_request_id:id,p_notes:String(notes||'').trim().slice(0,1000)}});const rejectedId=Array.isArray(result)?result[0]??null:result;if(!rejectedId)throw new Error('A solicitação não pôde ser rejeitada. Verifique se ela ainda está pendente.');return rejectedId}
async function createMerchantRequest(input={}){const p=await currentProfile();if(!p)throw new Error('Perfil não encontrado.');const name=String(input.business_name||'').trim().slice(0,180);if(name.length<2)throw new Error('Informe o nome da empresa.');const body={profile_id:p.id,city_id:String(input.city_id||'').trim(),business_name:name,status:'pending'};const document=String(input.document||'').replace(/\D/g,'').slice(0,14);const whatsapp=String(input.whatsapp||'').replace(/\D/g,'').slice(0,15);if(document)body.document=document;if(whatsapp)body.whatsapp=whatsapp;if(input.category_id)body.category_id=String(input.category_id);const rows=await dataRequest('merchant_requests',{method:'POST',body,prefer:'return=representation'});return Array.isArray(rows)?rows[0]||null:null}
async function ownBusinesses(){const rows=await dataRequest('businesses',{query:'?select=id,city_id,owner_profile_id,category_id,name,slug,description,logo_url,cover_url,whatsapp,phone,email,instagram,website,verified,featured,active,created_at,updated_at&order=created_at.asc'});return Array.isArray(rows)?rows:[]}async function ownBusiness(){const rows=await ownBusinesses();return rows[0]||null}
async function requireOwnBusiness(){const p=await currentProfile(),b=await ownBusiness();if(!p?.active||!b||b.owner_profile_id!==p.id)throw new Error('Nenhuma empresa vinculada a esta conta.');return b}
async function ownProducts(){const b=await requireOwnBusiness();const rows=await dataRequest('products',{query:`?select=id,business_id,category_id,name,slug,description,sku,price,promotional_price,stock_quantity,in_stock,featured,active,created_at,updated_at&business_id=eq.${enc(b.id)}&order=updated_at.desc`});return Array.isArray(rows)?rows:[]}
function productPayload(input,businessId){const name=String(input.name||'').trim().slice(0,180);if(name.length<2)throw new Error('Informe o nome do produto.');const price=input.price===''||input.price==null?null:Number(input.price),promo=input.promotional_price===''||input.promotional_price==null?null:Number(input.promotional_price),stock=input.stock_quantity===''||input.stock_quantity==null?null:Number(input.stock_quantity);if(price!==null&&(!Number.isFinite(price)||price<0))throw new Error('Preço inválido.');if(promo!==null&&(!Number.isFinite(promo)||promo<0))throw new Error('Preço promocional inválido.');if(price!==null&&promo!==null&&promo>price)throw new Error('O preço promocional não pode ser maior que o preço normal.');if(stock!==null&&(!Number.isInteger(stock)||stock<0))throw new Error('Estoque inválido.');return{business_id:businessId,category_id:input.category_id||null,name,slug:slugify(input.slug||name),description:String(input.description||'').trim().slice(0,5000)||null,sku:String(input.sku||'').trim().slice(0,100)||null,price,promotional_price:promo,stock_quantity:stock,in_stock:Boolean(input.in_stock),featured:Boolean(input.featured),active:input.active!==false,updated_at:new Date().toISOString()}}
async function createProduct(input={}){const b=await requireOwnBusiness(),body=productPayload(input,b.id);const rows=await dataRequest('products',{method:'POST',body,prefer:'return=representation'});return Array.isArray(rows)?rows[0]||null:null}
async function updateProduct(id,input={}){const b=await requireOwnBusiness(),pid=String(id||'');const body=productPayload(input,b.id);delete body.business_id;const rows=await dataRequest('products',{method:'PATCH',query:`?id=eq.${enc(pid)}&business_id=eq.${enc(b.id)}`,body,prefer:'return=representation'});return Array.isArray(rows)?rows[0]||null:null}
async function setProductActive(id,active){const b=await requireOwnBusiness(),rows=await dataRequest('products',{method:'PATCH',query:`?id=eq.${enc(id)}&business_id=eq.${enc(b.id)}`,body:{active:Boolean(active),updated_at:new Date().toISOString()},prefer:'return=representation'});return Array.isArray(rows)?rows[0]||null:null}
async function deleteProduct(id){const b=await requireOwnBusiness();await dataRequest('products',{method:'DELETE',query:`?id=eq.${enc(id)}&business_id=eq.${enc(b.id)}`,prefer:'return=minimal'});return true}
async function signOut(){try{return await authRequest('/sign-out',{method:'POST',body:'{}'})}finally{cachedJwt=null}}
window.ArapongasDigitalAuth={baseUrl:ARAPONGAS_AUTH,dataApiUrl:ARAPONGAS_DATA,session,jwt,signIn:(email,password)=>authRequest('/sign-in/email',{method:'POST',body:JSON.stringify({email,password})}),signUp:(name,email,password)=>authRequest('/sign-up/email',{method:'POST',body:JSON.stringify({name,email,password})}),signOut,currentProfile,requireAdmin,ensureProfile,updateProfile,dataRequest,merchantRequests,adminMerchantRequests,approveMerchantRequest,rejectMerchantRequest,createMerchantRequest,ownBusinesses,ownBusiness,requireOwnBusiness,ownProducts,createProduct,updateProduct,setProductActive,deleteProduct,slugify};
